name    'deric-sudoers'
version '0.0.2'
source 'https://github.com/deric/puppet-sudoers.git'
author 'deric'
license 'GNU LESSER GENERAL PUBLIC LICENSE, Version 3'
summary 'sudoers management'
description 'sudoers installation and configuration module'
project_page 'https://github.com/deric/puppet-sudoers.git'

dependency 'puppetlabs/stdlib', '>= 2.1.0'
